<template>
  <div class="page-wrapper">
    <h1 class="page-title">Terms & Conditions</h1>
    <p class="page-content">
      Introduction This document is an electronic record in terms of Information
      Technology Act, 2000 and rules there under as applicable. This electronic
      record is generated by a computer system and does not require any physical
      or digital signatures. This document is published in accordance with the
      provisions of Rule 3 (1) of the Information Technology (Intermediaries
      guidelines) Rules, 2011 that require publishing the rules and regulations,
      privacy policy and terms of use for access or usage of this mobile
      application (“App”). The website is owned and controlled by Hypd Marketing
      Technologies Private Limited, a company incorporated under the Companies
      Act, 2013 with its registered office at E-297 (FF & TF), Greater Kailash,
      New Delhi, New Delhi -110048 IN, India (“Hypd”). These terms of use
      (“Terms”), including the various policies incorporated by reference in
      these Terms, govern your access to and use of this website and the
      underlying services provided by us through the website, including our SMS,
      APIs, email notifications, applications, buttons, widgets, ads, commerce
      services, and our other covered services that may link to these Terms
      (collectively, the “Services”), and any information, text, graphics,
      photos or other materials uploaded, downloaded or appearing on or as a
      part of the Services (collectively referred to as “Content”). Your access
      to and use of the Services, however accessed, constitutes your agreement
      to be bound by these Terms, which establishes a contractual relationship
      between You and Hypd. When You use any of the Services provided by Us
      through the App, you will be subject to the rules, guidelines, policies,
      terms, and conditions applicable to such Service, and they shall be deemed
      to be incorporated into and shall apply in addition to these Terms. If you
      transact on our website, you shall be subject to the policies that are
      applicable for such transaction. By accessing the website, these terms
      will automatically apply to you. If you have any questions regarding our
      services, you can email us at care@hypd.in Changes to the Agreements We
      reserve the right, at our sole discretion, to change, modify, add or
      remove portions of these Terms, at any time without any prior written
      notice to you. It is your responsibility to review these Terms
      periodically for updates / changes. Your continued use of the website
      following the posting of changes will mean that you accept and agree to
      the revisions. As long as you comply with these terms, we grant you a
      personal, non-exclusive, non-transferable, limited privilege to access and
      use the services. In the event a special feature with its own terms and
      conditions is offered, the same shall apply in addition to these terms. In
      case of a conflict of the terms and conditions of such special feature
      with these terms, the terms specific to the special feature shall prevail.
      In these Terms, unless the context otherwise requires, references to:
      “Buyer”, shall mean a User who has agreed to become a buyer by using the
      Services to place an order for Samples or Products; “Products” shall mean
      products listed on the website [by Sellers] as a part of the Services, for
      purchase by Buyers; “Seller” shall mean a user who has executed a
      [merchant agreement] with us for the listing of products manufactured by
      it on the website, to be offered for sale or made available for purchase
      or for delivery on a sampling basis and free of cost, as a part of the
      services to the prospective Buyers, and who has agreed to register on the
      website as a seller for this purpose; “We”, “we”, “Us”, “us” or “Hypd”,
      shall mean Hypd Marketing Technologies Private Limited, its affiliates,
      permitted assigns and partners, and the terms “Our” and “our” shall be
      construed accordingly; and “You”, “you”, “User” or “user”, shall mean any
      natural or legal person who has agreed to become an end user by accessing
      the Contents of the website, or using the website or the Services offered
      through the website, by providing some personal information (more
      particularly described in the Privacy Policy and including but not limited
      to your name, address, mobile phone number and age, as well as at least
      one valid payment method (either a credit card or accepted payment
      partner) while registering on the website (“Registration Data”), and the
      terms “Your” and “your” shall be construed accordingly. Membership
      Eligibility Use of the Services is available only to persons who can form
      legally binding contracts under Indian Contract Act, 1872. If you are a
      minor, i.e., under the age of 18 years, or are otherwise ‘incompetent to
      contract’ under the Indian Contract Act, 1872, you are not eligible to use
      the Services and you shall not register as a User of or transact on the
      App. If minors wish to transact on the App, all transactions shall be
      required to be made by their legal guardians/parents who must be
      registered Users of the App. We reserve the right to terminate your
      membership and/or refuse to provide you with access to the Services if it
      is brought to our notice or if it is discovered that you are under the age
      of 18 years or are ‘incompetent to contract’. The Services The website is
      only a medium that provides access to a technology platform, managed by
      Hypd, which enables Users to meet and interact with one another, content,
      and products for their transactions. It is a marketplace for the listing
      of Products and offering for sale various Products, by the Sellers, and
      for the purchase of Products, by the Buyers. Hypd is an intermediary for
      all such transactions and is not a party to nor controls in any manner any
      transaction between the website Users. You agree that Hypd is only
      providing a platform for communication and it is agreed that any contract
      for sale or delivery of any of the Products or Samples, as may be
      applicable, shall be a strictly bipartite contract between the Seller and
      the Buyer, for which Hypd will only be fulfilling the delivery of the
      relevant Product or Sample, strictly on behalf of the Seller. Hypd, its
      affiliates, permitted assigns or partners are not liable for anything
      whatsoever that is undertaken using this platform and: All
      commercial/contractual terms are offered by and agreed to between Buyers
      and Sellers alone. The commercial/contractual terms in relation to
      Products include, without limitation, the price, shipping costs, payment
      methods, payment terms, date, period and mode of delivery, warranties
      related to Products and after sales services related to Products. Hypd
      does not have any control in respect of the offering or acceptance of such
      commercial/contractual terms between the Buyers and Sellers. Hypd does not
      make any representation or warranty as to specifications (such as quality,
      value, saleability, etc) of the Products proposed to be offered for sale
      and purchased or ordered as Samples, through the App. Hypd does in any
      manner endorse the sale or purchase of any Products or Samples through the
      website. Hypd accepts no liability for any errors or omissions, whether on
      behalf of itself or third parties. Hypd is not responsible for any
      non-performance or breach of any contract entered into between Buyers and
      Sellers. Hypd cannot and does not guarantee that the concerned Buyers
      and/or Sellers will perform any transaction concluded through the website.
      Hypd shall not and is not required to mediate or resolve any dispute or
      disagreement between Buyers and Sellers. Hypd does not make any
      representation or warranty as to the item-specifics (such as legal title,
      creditworthiness, identity, etc.) of any of its users. You are advised to
      independently verify the bona fides of any user that You choose to deal
      with through the App and use Your best judgment in that regard. Hypd does
      not hold any right, title or interest over the Products or Samples nor
      shall Hypd have any obligations or liabilities in respect of any
      transaction or contract entered between Buyers and Sellers. Hypd shall
      provide logistics services wherein our delivery partners shall deliver to
      the Buyers, the Products and Samples ordered through the App by the
      Buyers. Subject to Clause 3.8 above, Hypd does not, at any point of time
      during any transaction between the Buyer and the Seller through the App,
      come into or take possession of any of the Products offered by the Seller
      nor does it, at any point, gain title to or have any right or claim over
      the Products offered by the Seller to the Buyer. It does, however, provide
      warehousing services for Samples and products as a part of its Services to
      the Sellers but does not, in any point in time, gain title to or have any
      right or claim over the Samples or products offered by the Sellers to the
      prospective Buyers. You shall independently agree upon the manner and
      terms and conditions of delivery, payment, insurance etc. with the
      Seller(s) that You transact with. Disclaimer: In the event the pricing on
      any Product is reflected incorrectly on the website due to some technical
      issue, typographical error or the Product information published on the
      website is incorrectly displayed or provided by the Seller, the Seller may
      cancel your order. You release and indemnify Hypd and/or any of its
      officers and representatives from any cost, damage, liability or other
      consequence of any of the actions of all Users of the website and
      specifically waive any claims that you may have in this behalf under any
      applicable law. Notwithstanding its reasonable efforts in that behalf,
      Hypd cannot take responsibility or control the information provided by the
      Users which is made available through the website. You may find any other
      User's information to be offensive, harmful, inconsistent, inaccurate, or
      deceptive. Please use caution and practice safe trading when using the
      Services. Please note that there could be risks in dealing with underage
      persons or people acting under false pretence. Privacy Policy Any
      information that you or other Users provide to Hypd is subject to our
      Privacy Policy, which governs our collection and use of your information.
      You understand that through your use of the Services, you have read and
      fully understand the Privacy Policy of Hypd and you consent to the
      collection and use (as set forth in the Privacy Policy) of this
      information, including the transfer of this information to third parties
      for storage, processing and use by Hypd. As part of providing you the
      Services, we may need to provide you with certain communications, such as
      service announcements and administrative messages via e-mail and short
      messaging service (SMS) or any other mode of communication, electronic or
      otherwise. These communications are considered part of the Services and
      your account, which you may not be able to opt-out from receiving. Tip:
      You can control most communications from the Services, including
      notifications about orders placed by you, promotions, advertisements,
      comments or other activity on any Content posted by you and periodical
      updates from us, provided to you as and when required. Please see your
      settings for email and mobile notifications for more. The user hereby
      consents, expresses and agrees that he has read and fully understands the
      Privacy Policy of Hypd. The User further consents that the terms and
      contents of such Privacy Policy are acceptable to him. Limited Use The
      User agrees and undertakes not to reverse engineer, modify, copy,
      distribute, transmit, display, perform, reproduce, publish, license,
      create derivative works from, transfer, or sell any information or
      software obtained through the App. Limited reproduction and copying of the
      Content is permitted provided that Hypd’s name is stated as the source and
      prior written permission of Hypd is sought. For the removal of any doubt,
      it is clarified that unlimited or complete reproduction, copying of the
      content for commercial or non-commercial purposes and unwarranted
      modification of data and information within the content of the website is
      not permitted. Throughout these Terms, Hypd’s prior written consent means
      a communication issued by Hypd’s legal department, specifically in
      response to Your request, and specifically addressing the activity or
      conduct for which You seek authorisation. Use of the Services You agree,
      undertake and confirm that your access to and use of the Services shall be
      strictly governed by the following binding principles: You shall not host,
      display, upload, modify, publish, transmit, update or share any
      information which: belongs to another person and to which You does not
      have any right to; is grossly harmful, harassing, blasphemous, defamatory,
      obscene, pornographic, pedophilic, libellous, invasive of another's
      privacy, hateful, or racially, ethnically objectionable, disparaging,
      relating or encouraging money laundering or gambling, or otherwise
      unlawful in any manner whatever; or unlawfully threatening or unlawfully
      harassing including but not limited to “indecent representation of women”
      within the meaning of the Indecent Representation of Women (Prohibition)
      Act, 1986; is misleading in any way; is patently offensive to the online
      community, such as sexually explicit content, or content that promotes
      obscenity, pedophilia, racism, bigotry, hatred, or physical harm of any
      kind against any group or individual; harasses or advocates harassment of
      another person; involves the transmission of “junk mail”, “chain letters”,
      or unsolicited mass mailing or “spamming”; promotes illegal activities or
      conduct that is abusive, threatening, obscene, blasphemous, politically or
      religiously charged, defamatory or libellous; infringes upon or violates
      any third party's rights including, but not limited to, intellectual
      property rights, rights of privacy (including without limitation
      unauthorised disclosure of a person's name, email address, physical
      address or phone number) or rights of publicity); promotes an illegal or
      unauthorised copy of another person's copyrighted work, such as providing
      pirated computer programs or links to them, providing information to
      circumvent manufacture-installed copy-protect devices, or providing
      pirated music or links to pirated music files; contains restricted or
      password-only access pages, or hidden pages or images (those not linked to
      or from another accessible page); provides material that exploits people
      in a sexual, violent or otherwise inappropriate manner or solicits
      personal information from anyone; provides instructional information about
      illegal activities such as making or buying illegal weapons, violating
      someone's privacy, or providing or creating computer viruses; contains
      video, photographs, or images of another person (with a minor or an
      adult). tries to gain unauthorised access or exceeds the scope of
      authorised access to any of the Services or to profiles, blogs,
      communities, account information, bulletins, friend request, or other
      areas of the App or solicits passwords or personal identifying information
      for commercial or unlawful purposes from other users; engages in
      commercial activities and/or sales without our prior written consent such
      as contests, sweepstakes, barter, advertising and pyramid schemes, or the
      buying or selling of “virtual” products related to the Services; solicits
      gambling or engages in any gambling activity which we, in Our sole
      discretion, believes is or could be construed as being illegal; interferes
      with another User's use and enjoyment of the Services; refers to any
      content, website or URL that, at our sole discretion, contains material
      that is inappropriate for the App, contains content that would be
      prohibited or violates the letter or spirit of these Terms; harm minors in
      any way; infringes any patent, trademark, copyright or other proprietary
      rights or third party's trade secrets or rights of publicity or privacy or
      shall not be fraudulent or involve the sale of counterfeit or stolen
      Products or Samples; violates any law for the time being in force;
      deceives or misleads the addressee/ users about the origin of such
      messages or communicates any information which is grossly offensive or
      menacing in nature; impersonate another person; contains software viruses
      or any other computer code, files or programs designed to interrupt,
      destroy or limit the functionality of any computer resource; or contains
      any trojan horses, worms, time bombs, cancelbots, easter eggs or other
      computer programming routines that may damage, detrimentally interfere
      with, diminish value of, surreptitiously intercept or expropriate any
      system, data or personal information; threatens the unity, integrity,
      defence, security or sovereignty of India, friendly relations with foreign
      states, or public order or causes incitement to the commission of any
      cognizable offence or prevents investigation of any offence or is
      insulting any other nation; shall not be false, inaccurate or misleading;
      shall not, directly or indirectly, offer, attempt to offer, trade or
      attempt to trade in any item, the dealing of which is prohibited or
      restricted in any manner under the provisions of any applicable law, rule,
      regulation or guideline for the time being in force. shall not create
      liability for us or cause us to lose (in whole or in part) the services of
      our internet service provider (“ISPs”) or other suppliers; You shall not
      use any program, algorithm or methodology, or any similar or equivalent
      manual process, to copy or, in any way reproduce or circumvent the
      navigational structure or presentation of the Content on the App, to
      obtain or attempt to obtain any data or information about the App or the
      Content through any means other than that which has been purposely made
      available through the App. We reserve our right to bar any such activity.
      You shall not attempt to gain unauthorised access to any portion or
      feature of the App, or any other systems or networks connected to the App,
      by hacking, password 'mining' or any other illegitimate means. You shall
      not probe, scan or test the vulnerability of the App or any network
      connected to the App nor breach the security or authentication measures on
      the App or any network connected to the App. You may not reverse look-up,
      trace or seek to trace any information on any other User of or visitor to
      App, or any other customer, including any account on the App not owned by
      You, to its source, or exploit the App or any service or information made
      available or offered by or through the App, in any way where the purpose
      is to reveal any information, including but not limited to personal
      identification or information, other than Your own information, as
      provided for by the App. You shall not make any negative, denigrating or
      defamatory statement(s) or comment(s) about us or the brand name or domain
      name used by us including the terms Hypd and Hypd.in, hypd.store, or
      otherwise engage in any conduct or action that might tarnish the image or
      reputation of Hypd or any Seller on the platform or otherwise tarnish or
      dilute any of Hypd’s trade or service marks, trade name and/or goodwill
      associated with such trade or service marks, trade name as may be owned or
      used by us. You agree that you will not take any action that imposes an
      unreasonable or disproportionately large load on the infrastructure of the
      App or Hypd’s systems or networks, or any systems or networks connected to
      Hypd. You agree not to use any device, software or routine to interfere or
      attempt to interfere with the proper working of the App or any transaction
      being conducted on the App, or with any other person's use of the App. You
      may not forge headers or otherwise manipulate identifiers in order to
      disguise the origin of any message or transmittal you send to us on or
      through the App or any service offered on or through the App. You may not
      pretend that you are, or that you represent, someone else, or impersonate
      any other individual or entity or access the App through another user's
      account, unless authorised to do so You may not use the App or any content
      for any purpose that is unlawful or prohibited by these Terms, or to
      solicit the performance of any illegal activity or other activity which
      infringes the rights of Hypd and/or others. You shall, at all times,
      ensure full compliance with the applicable provisions of the Information
      Technology Act, 2000 and rules thereunder as applicable and as amended
      from time to time and also all applicable domestic laws, rules and
      regulations (including the provisions of any applicable exchange control
      laws or regulations in force) and international laws, foreign exchange
      laws, statutes, ordinances and regulations (including, but not GST, custom
      duty, local levies) regarding your use of the Services and your listing,
      purchase, solicitation of offers to purchase, or offers of sale in respect
      of Products or Samples, as may be applicable. You shall not engage in any
      transaction on any Product or Sample, which is prohibited by the
      provisions of any applicable law including exchange control laws or
      regulations for the time being in force. You agree to grant us a
      non-exclusive, worldwide, perpetual, irrevocable, royalty-free,
      sub-licensable (through multiple tiers) right to exercise the copyright,
      publicity, database rights or any other rights you have in your
      information, or in any media now known or not currently known, with
      respect to your information. We will only use your information in
      accordance with these Terms and the Privacy Policy applicable to your use
      of the Services From time to time, you shall be responsible for providing
      information relating to the products or services proposed to be sold by
      you. In this connection, you undertake that all such information shall be
      accurate in all respects. You shall not exaggerate or over emphasise the
      attributes of such products or services so as to mislead other users in
      any manner. You shall not engage in advertising to, or solicitation of,
      other users of the Services to buy or sell any products or services,
      including, but not limited to, products or services related to those being
      displayed on the App or related to us. You may not transmit any chain
      letters or unsolicited commercial or junk email to other Users via the
      App. It shall be a violation of these Terms to use any information
      obtained from the App in order to harass, abuse, or harm another person,
      or in order to contact, advertise to, solicit, or sell to another person
      other than us without our prior explicit consent. In order to protect our
      Users from such advertising or solicitation, we reserve the right to
      restrict the messages or emails which a user may send to other Users in
      any 24-hour period to a number which we deem appropriate in our sole
      discretion. You understand that we have the right at all times to disclose
      any information (including the identity of the persons providing
      information or materials on the App) as necessary to satisfy any law,
      regulation or valid governmental request. This may include, without
      limitation, disclosure of the information in connection with investigation
      of alleged illegal activity or solicitation of illegal activity or in
      response to a lawful court order or subpoena. In addition, we can (and you
      hereby expressly authorise us to) disclose any information about You to
      law enforcement or other government officials, as we, in our sole
      discretion, believe necessary or appropriate in connection with the
      investigation and/or resolution of possible crimes, especially those that
      may involve personal injury. We reserve the right, but have no obligation,
      to monitor the materials posted on the website. Hypd shall have the right
      to remove or edit any content that in its sole discretion violates, or is
      alleged to violate, any applicable law or either the spirit or letter of
      these Terms. Notwithstanding this right, you remain solely responsible for
      the content of the materials you post on the App and in your private
      messages. Please be advised that such Content posted does not necessarily
      reflect Hypd’s views. In no event shall Hypd assume or have any
      responsibility or liability for any Content posted or for any claims,
      damages or losses resulting from use of Content and/or appearance of
      Content on the App. You hereby represent and warrant that you have all
      necessary rights in and to all Content which you provide and all
      information it contains and that such Content shall not infringe any
      proprietary or other rights of third parties or contain any libellous,
      tortious, or otherwise unlawful information. It is possible that other
      users (including unauthorised users or 'hackers') may post or transmit
      offensive or obscene materials on the App and that You may be
      involuntarily exposed to such offensive and obscene materials. It also is
      possible for others to obtain personal information about you due to your
      use of the App, and that the recipient may use such information to harass
      or injure you. We do not approve of such unauthorised uses, but by using
      the App You acknowledge and agree that we are not responsible for the use
      of any personal information that you publicly disclose or share with
      others on the App. Please carefully select the type of information that
      you publicly disclose or share with others on the App Your correspondence
      or business dealings with, or participation in promotions of, advertisers
      found on or through the App, including payment and delivery of related
      products or services, and any other terms, conditions, warranties or
      representations associated with such dealings, are solely between you and
      such advertiser. We shall not be responsible or liable for any loss or
      damage of any sort incurred as the result of any such dealings or as the
      result of the presence of such advertisers on the App. 9. No Compensation
      If the quality of any Products, information, or other material purchased
      or obtained by you through the App did not meet the Product specifications
      displayed on the App, no compensation will be given other than the return
      and refund or exchange of the Product as per these Terms. If the quality
      of any Samples ordered through the App did not meet your expectations, no
      compensation will be given other than the replacement of the Sample as per
      these Terms. The Buyer cannot request compensation from Hypd for any
      reason, including but not limited to: any variation in the finish or
      appearance of the final Product or Sample; any delay in delivery caused by
      unforeseen circumstances; any special, incidental, indirect or
      consequential damage of any kind caused by a Product or a Sample,
      including any reactions to skin or other body parts, missed opportunities
      to avail certain discounts; any issue with our delivery partners or their
      personnel, any voucher which got deactivated due to the end of expiry
      date; unavailability of items which the Buyer tried to purchase, etc.
      Unreasonable and unlawful requests for compensation, over and above the
      entitled refund, will be treated as loss to business cases. Hypd holds the
      rights to cancel orders and block accounts of such customers without any
      prior notice. Contents Posted on the App All Content, whether publicly
      posted or privately transmitted, is the sole responsibility of the person
      who originated such Content. We may not monitor or control the Content
      posted via the Services and, we cannot take responsibility for such
      Content. Any use or reliance on any Content or materials posted via the
      Services or obtained by you through the Services is at your own risk as
      Hypd is merely an intermediary for the purposes of these Terms. Except as
      expressly provided in these Terms, no part of the Services and no part of
      the Content may be copied, reproduced, republished, uploaded, posted,
      publicly displayed, encoded, translated, transmitted or distributed in any
      way (including “mirroring”) to the App or any other computer, server,
      application, website or other medium for publication or distribution or
      for any commercial enterprise, without Hypd’s express prior written
      consent. You may use information on the Products and Samples purposely
      made available through the App for downloading, provided that You: do not
      remove any proprietary notice language in all copies of such documents;
      use such information only for your personal, non-commercial informational
      purpose and do not copy or post such information on any networked computer
      or broadcast it in any media; make no modifications to any such
      information; and do not make any additional representations or warranties
      relating to such documents. You shall be responsible for any such Content
      that you may transmit to and via or post through the App. Such Content
      will become our property and You grant us the worldwide, perpetual and
      transferable rights in such Content. We shall be entitled to, consistent
      with our Privacy Policy as adopted in accordance with applicable law, use
      the Content or any of its elements for any type of use forever, including
      but not limited to promotional and advertising purposes and in any media
      whether now known or hereafter devised, including the creation of
      derivative works that may include the Content You provide. You agree that
      any Content You post may be used by us, consistent with our Privacy Policy
      and rules relating to Your Use of the Services as mentioned herein, and
      You are not entitled to any payment or other compensation for such use.
      Links The Services may contain links to third-party websites or resources.
      You acknowledge and agree that Hypd is not responsible or liable for: (i)
      the availability or accuracy of such websites or resources; or (ii) the
      content, products, or services on or available from such websites or
      resources. Links to such websites or resources do not imply any
      endorsement by Hypd of such websites or resources or the content,
      products, or services available from such websites or resources. You
      acknowledge sole responsibility for and assume all risk arising from your
      use of any such websites or resources. 12. User Warranty and
      Representation You guarantee, warrant, and certify that you are the owner
      of the content which you submit or otherwise authorise us to use and that
      the content does not infringe upon the intellectual property rights or
      other rights of third parties. You further warrant that to your knowledge,
      no action, suit, proceeding, or investigation has been instituted or
      threatened relating to any content, including trademark, trade name
      service mark, and copyright formerly or currently used by you in
      connection with the Services rendered through the App. Exactness Not
      Guaranteed We do not warrant that any Product or Sample description or
      other Content made available through the App is accurate, complete,
      reliable, current, or error-free and assume no liability in this regard.
      Hypd hereby disclaims any guarantees of exactness as to the finish and
      appearance of the final Product or Sample as ordered by the User through
      the App. Intellectual Property Rights Unless otherwise indicated or
      anything contained to the contrary or any proprietary material owned by a
      third party and so expressly mentioned, the Services contains content to
      which Hypd owns all intellectual property rights, including, without
      limitation, any and all rights, title and interest in and to copyright,
      related rights, patents, utility models, trademarks, trade names, service
      marks, designs, know-how, trade secrets and inventions (whether patentable
      or not), goodwill, source code, meta tags, databases, text, content,
      graphics, icons, and hyperlinks (“Hypd Content”). You acknowledge and
      agree that you shall not use, copy, imitate, reproduce or distribute any
      Hypd Content without obtaining authorisation from Hypd Notwithstanding the
      foregoing, it is expressly clarified that you will retain ownership and
      shall solely be responsible for any Content that you provide or upload
      when using any Service, including any text, data, information, images,
      photographs, music, sound, video or any other material which you may
      upload, transmit or store when making use of our various Services.
      Instead, you hereby grant to Hypd a non-exclusive, fully paid and
      royalty-free, transferable, sub-licensable, worldwide license to use the
      Content that you post on or through the Service, subject to Hypd’s Privacy
      Policy. Some of the Service is supported by advertising revenue and may
      display advertisements and promotions, and you hereby agree that Hypd may
      place such advertising and promotions on the Service or on, about, or in
      conjunction with your Content. The manner, mode and extent of such
      advertising and promotions are subject to change without specific notice
      to you. You acknowledge that we may not always identify paid services,
      sponsored content, or commercial communications as such. Disclaimers and
      Limitations of Liability Please read this section carefully as it limits
      the liability of Hypd and its parents, subsidiaries, affiliates, related
      companies, officers, directors, employees, agents, representatives,
      partners, and licensors (collectively, the “Hypd Entities”). Each of the
      subsections below only applies up to the maximum extent permitted under
      applicable law. Nothing in this section is intended to limit any rights
      you may have which may not be lawfully limited. Your access to and use of
      the Services or any Content are at your own risk. You understand and agree
      that the Services are provided to you on an “AS IS” and “AS AVAILABLE”
      basis without any representation or warranties, express or implied except
      otherwise specified in writing. Without limiting the foregoing, to the
      maximum extent permitted under applicable law, THE Hypd ENTITIES DISCLAIM
      ALL WARRANTIES AND CONDITIONS, WHETHER EXPRESS OR IMPLIED, OF
      MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE, OR NON-INFRINGEMENT.
      Without prejudice to the foregoing, the Hypd Entities make no warranty or
      representation and disclaim all responsibility and liability for: (i) the
      completeness, accuracy, availability, timeliness, security or reliability
      of the Services or any Content; (ii) any harm to your computer system,
      loss of data, or other harm that results from your access to or use of the
      Services or any Content; (iii) the deletion of, or the failure to store or
      to transmit, any Content and other communications maintained by the
      Services; and (iv) whether the Services will meet your requirements or be
      available on an uninterrupted, secure, or error-free basis. No advice or
      information, whether oral or written, obtained from the Hypd Entities or
      through the Services, will create any warranty or representation not
      expressly made herein. Limitation of Liability TO THE MAXIMUM EXTENT
      PERMITTED BY APPLICABLE LAW, THE Hypd ENTITIES SHALL NOT BE LIABLE FOR ANY
      INDIRECT, INCIDENTAL, SPECIAL, CONSEQUENTIAL OR PUNITIVE DAMAGES, OR ANY
      LOSS OF PROFITS OR REVENUES, WHETHER INCURRED DIRECTLY OR INDIRECTLY, OR
      ANY LOSS OF DATA, USE, GOOD-WILL, OR OTHER INTANGIBLE LOSSES, RESULTING
      FROM (i) YOUR ACCESS TO OR USE OF OR INABILITY TO ACCESS OR USE THE
      SERVICES; (ii) ANY CONDUCT OR CONTENT OF ANY THIRD PARTY ON THE SERVICES,
      INCLUDING WITHOUT LIMITATION, ANY DEFAMATORY, OFFENSIVE OR ILLEGAL CONDUCT
      OF OTHER USERS OR THIRD PARTIES; (iii) ANY CONTENT OBTAINED FROM THE
      SERVICES; OR (iv) UNAUTHORISED ACCESS, USE OR ALTERATION OF YOUR
      TRANSMISSIONS OR CONTENT. IN NO EVENT SHALL THE AGGREGATE LIABILITY OF THE
      Hypd ENTITIES EXCEED THE AMOUNT YOU PAID Hypd, IF ANY, IN THE PAST SIX
      MONTHS FOR THE SERVICES GIVING RISE TO THE CLAIM. THE LIMITATIONS OF THIS
      SUBSECTION SHALL APPLY TO ANY THEORY OF LIABILITY, WHETHER BASED ON
      WARRANTY, CONTRACT, STATUTE, TORT (INCLUDING NEGLIGENCE) OR OTHERWISE, AND
      WHETHER OR NOT THE Hypd ENTITIES HAVE BEEN INFORMED OF THE POSSIBILITY OF
      ANY SUCH DAMAGE, AND EVEN IF A REMEDY SET FORTH HEREIN IS FOUND TO HAVE
      FAILED OF ITS ESSENTIAL PURPOSE. Nothing on the App constitutes, or is
      meant to constitute, advice of any kind. All the Products sold through the
      App are governed by different state laws and if the Seller or Hypd is
      unable to deliver such Products due to implications of different state
      laws, the Seller will return or will give credit for the amount (if any)
      received in advance by Seller from the sale of such Product that could not
      be delivered to you. There shall be no compensation, whether by way of
      credit or refund, in respect of Samples as all Samples are delivered free
      of cost. The Users of the App are expected to update his/her said app on
      regular basis, so that he/she can avail the latest services and is duly
      aware of any change(s) in the Hypd policy. By registering your phone
      number with us, You consent to be contacted by Us via phone calls and/or
      SMS and/or Pop-up notifications, in case of any order or shipment or
      delivery related updates. In the event of failure to update the App by the
      User, the Users understands and agrees that Hypd shall not be liable in
      any manner whatsoever. Indemnification You agree to indemnify, defend and
      hold harmless Hypd, its associates and partners from and against any and
      all losses, liabilities, claims, damages, costs and expenses (including
      legal fees and disbursements in connection therewith and interest
      chargeable thereon) asserted against or incurred by Hypd that arise out
      of, result from, or may be payable by virtue of, any breach or a law or
      any right of any user including including but not limited to intellectual
      property rights of a third party or a user or non-performance of any
      representation, warranty, covenant or obligation to be performed by you
      pursuant to these Terms. Seller’s Obligations As a Seller registered on
      the App, you are allowed to list any Product(s) for sale through the App
      in accordance with the Policies which are incorporated by way of reference
      in these Terms. You must be legally able to sell the Product(s) you list
      for sale on our App. You must ensure that the listed Products do not
      infringe upon the intellectual property, trade secret or other proprietary
      rights or publicity or privacy rights of third parties. Listings may only
      include text descriptions, graphics and pictures that describe your
      Product for sale. All listed Products must be listed in an appropriate
      category through the App. All listed Products must be kept in stock with
      the Seller for successful fulfilment of sales. As a Seller registered on
      the App, you are allowed to list any Sample(s) through the App in
      accordance with the Policies which are incorporated by way of reference in
      these Terms. You must be legally able to list and distribute the Sample(s)
      you list on our App. You must ensure that the listed Samples do not
      infringe upon the intellectual property, trade secret or other proprietary
      rights or publicity or privacy rights of third parties. Listings may only
      include text descriptions, graphics and pictures that describe your
      Sample. All listed Samples must be listed in the appropriate category in
      the Samples section on the App. You are requested to ship the Sample(s)
      proposed to be listed by you on the App, to the designated warehouse
      address provided by Hypd at least 5 (five) working days prior to such
      listing, unless otherwise agreed by Hypd in writing. The listing
      description of the relevant item must not be misleading and must describe
      actual condition of the Product or Sample, as may be applicable. If the
      item description does not match the actual condition of the item, you
      agree to refund any amounts that you may have received from the Buyer. You
      agree not to list a single Product or Sample in multiple quantities across
      various categories on the App. Hypd reserves the right to delete such
      multiple listings of the same Product or Sample listed by you in various
      categories. Payment While availing any of the payment method/s available
      through the App, we will not be responsible or assume any liability,
      whatsoever in respect of any loss or damage arising directly or indirectly
      to you due to: Lack of authorisation for any transaction(s), or Exceeding
      the preset limit mutually agreed by You and between ”Bank(s)”, or Any
      payment issues arising out of the transaction, or Decline of transaction
      for any other reason(s). All payments made against the purchases on App by
      You shall be compulsorily in Indian Rupees acceptable in the Republic of
      India. App will not facilitate transaction with respect to any other form
      of currency with respect to the purchases made on App. Before
      shipping/delivering your order to you, Seller may request you to provide
      supporting documents (including but not limited to Govt. issued ID and
      address proof) to establish the ownership of the payment instrument used
      by you for your purchase. This is done in the interest of providing a safe
      online shopping environment to our Users. Further: Transactions,
      transaction price and all commercial terms such as delivery, dispatch of
      Products are as per principal to principal bipartite contractual
      obligations between Buyer and Seller and payment facility is merely used
      by the Buyer and Seller to facilitate the completion of the transaction.
      Use of the payment facility shall not render Hypd, its associates or
      partners liable or responsible for the non-delivery, non-receipt,
      non-payment, damage, breach of representations and warranties,
      non-provision of after sales or warranty services or fraud as regards the
      Products listed on and purchased by Buyers through the App. You have
      specifically authorised Hypd and its service providers to collect,
      process, facilitate and remit payments and/or the transaction price
      electronically or through cash on delivery to and from other Users in
      respect of transactions through the relevant payment system (“Payment
      Facility”). Your relationship with Hypd is on a principal to principal
      basis and by accepting these Terms you agree that Hypd is an independent
      contractor for all purposes, and does not have control of or liability for
      the Products that are listed on App that are paid for by using the Payment
      Facility. Hypd does not guarantee the identity of any User nor does it
      ensure that a Buyer or a Seller will complete a transaction. You
      understand, accept and agree that the Payment Facility provided by Hypd is
      neither a banking nor financial service but is merely a facilitator
      providing an electronic, automated online electronic payment, receiving
      payment through cash on delivery, collection and remittance facility for
      the transactions through the App using the existing authorised banking
      infrastructure payment gateway networks. Further, by providing the Payment
      Facility, Hypd, its associates and partners are neither acting as trustees
      nor acting in a fiduciary capacity with respect to the transaction or the
      transaction price. Payment Facility for Buyers You, as a Buyer, understand
      that upon initiating a transaction You are entering into a legally binding
      and enforceable contract with the Seller to purchase the Product(s) from
      the Seller using the Payment Facility, and You shall pay the transaction
      price through Your issuing bank to the Seller using the Payment Facility.
      You, as a Buyer, may agree with the Seller through electronic
      communication and electronic records and using the automated features as
      may be provided by the Payment Facility on any extension / increase in the
      dispatch and/or delivery time and the transaction shall stand amended to
      such extent. Any such extension / increase of dispatch / delivery time or
      subsequent novation/variation of the transaction should be in compliance
      with the Payment Facility Rules and Policies. You, as a Buyer, shall
      electronically notify the payment system operation using the appropriate
      App features immediately upon delivery or non-delivery of any Product
      within the time period as provided in the Policies. Non-notification by
      You of delivery or non-delivery within the time period specified in the
      Policies shall be construed as a deemed delivery in respect of that
      transaction. In case of cash on delivery transactions, the Buyer is not
      required to confirm the receipt of Products. You, as a Buyer, shall be
      entitled to claim a refund of the transaction price (as Your sole and
      exclusive remedy) in case You do not receive the delivery within the time
      period agreed in the transaction or within the time period as provided in
      the Policies, whichever is earlier. In case you do not raise a refund
      claim using the App features within the stipulated time, then this would
      make You ineligible for a refund. You, as a Buyer, understand that the
      Payment Facility may not be available in full or in part for certain
      category of Products and/or transactions as mentioned in the Policies and
      hence, You may not be entitled to a refund in respect of the transactions
      for those Product. For electronic transactions, refund, if any, shall be
      made at the same issuing bank from where transaction price was received
      and such refund shall be made through the Payment Facility using NEFT /
      RTGS or any other online banking/electronic funds transfer system approved
      by Reserve Bank India (RBI). For cash on delivery transactions, refunds,
      if any, will be made via demand draft in favour of the Buyer (as per the
      registration details provided by the Buyer).[2] Refund shall be made in
      Indian Rupees only and shall be equivalent to the transaction price.
      Refund shall be conditional and shall be with recourse available to Hypd
      in case of any misuse by Buyer. Refund shall be subject to Buyer complying
      with applicable Policies. Hypd reserves the right to impose limits on the
      number of transactions or the transaction price which Hypd may receive
      from an individual’s valid credit/debit/cash card/valid bank account/and
      such other infrastructure or any other financial instrument directly or
      indirectly through payment aggregator or through any such facility
      authorised by Reserve Bank of India to provide enabling support facility
      for collection and remittance of payment or by an individual Buyer during
      any time period, and reserves the right to refuse to process transactions
      exceeding such limit Hypd reserves the right to refuse to process
      transactions by Buyers with a prior history of questionable charges
      including without limitation breach of any agreements by Buyer with Hypd
      or breach/violation of any law or any charges imposed by the respective
      issuing bank or breach of any policy. Hypd may do such checks as it deems
      fit before approving the receipt of/Buyer’s commitment to pay (for cash on
      delivery transactions) the transaction price from the Buyer for security
      or other reasons at the discretion of Hypd. As a result of such check, if
      Hypd is not satisfied with the creditability of the Buyer or the
      genuineness of the transaction/transaction price, it will have the right
      to reject the receipt of / Buyer’s commitment to pay the transaction
      price. Hypd may delay notifying the payment confirmation i.e. informing
      the Seller, if Hypd is not satisfied with the creditability of the Buyer
      or the genuineness of the transaction/transaction price or for Buyers
      conducting high transaction volumes in order to ensure safety and security
      in relation to the transaction. In addition, Hypd may hold the transaction
      price and Hypd may not inform the Seller to initiate dispatch of the
      Product or may remit the transaction price to law enforcement officials
      (instead of refunding the same to the Buyer) at the request of law
      enforcement officials in the event the Buyer is engaged in any form of
      illegal activity. The Buyer and Seller acknowledge that Hypd will not be
      liable for any damages, interests or claims, etc. resulting from not
      processing a transaction/transaction price or any delay in processing a
      transaction/transaction price which is beyond control of Hypd. Compliance
      with Laws: The Buyer and Seller shall comply with all applicable laws
      (including without limitation, the Foreign Exchange Management Act, 1999
      and the rules and notifications made and issued there under and the
      Exchange Control Manual as may be issued by Reserve Bank of India from
      time to time, the Customs Act, the Information and Technology Act, 2000 as
      amended by the Information Technology (Amendment) Act 2008, the Prevention
      of Money Laundering Act, 2002 and the rules made thereunder, the Foreign
      Contribution Regulation Act, 1976 and the rules made there under, the
      Income Tax Act, 1961 and the rules made there under, the Export Import
      Policy of government of India) applicable to them respectively for using
      Payment Facility and the App. Buyer’s arrangement with Issuing Bank: All
      valid credit /debit/cash card and other payment instruments are processed
      using a credit card payment gateway or appropriate payment system
      infrastructure and the same will also be governed by the terms and
      conditions agreed to between the Buyer and the respective issuing bank and
      the payment instrument issuing company. All online bank transfers from
      valid bank accounts are processed using the payment gateway provided by
      the respective issuing bank which supports the Payment Facility to provide
      these services to the Users. All such online bank transfers on the Payment
      Facility are also governed by the terms and conditions agreed to between
      Buyer and the respective Issuing Bank. Jurisdictional Issues/Sale in India
      Only Unless otherwise specified, the material through the Services is
      presented solely for the purpose of sale/ ordering in India. Hypd makes no
      representation that materials made available through the Services are
      appropriate or available for use in jurisdictions other than India. Those
      who choose to access this site from locations other than in India, do so
      on their own initiative and Hypd is not responsible for the supply of
      Products or Samples/refund for the Products/ replacement of the Samples
      ordered from other locations/countries other than India, or compliance
      with local laws, if and to the extent local laws are applicable.
      Trademark, Copyright and Restriction The Services are controlled and
      operated by Hypd, its partners and associates and Products and Samples are
      offered for sale or ordering by the respective Sellers. All material on
      this site, including images, illustrations, audio clips, and video clips,
      are protected by copyrights, trademarks, and other intellectual property
      rights. All content included on the App, such as text, graphics, logos,
      button icons, images, audio clips, digital downloads, data compilations,
      and software, is the property of Hypd or its Sellers, unless owned by any
      third party and protected by applicable copyright laws. All other such
      content not owned by Hypd that appears on the App is the property of the
      respective owners. All software used on this App is the property of Hypd
      and is protected by applicable copyright laws. Any unauthorised copying or
      reproduction of the above identified material is strictly prohibited by
      law. ‘Hypd’, the Hypd logo and other marks indicated on the App are
      trademarks of Hypd. Other Hypd graphics, logos, page headers, button
      icons, scripts, and service names are trademarks or trade dresses of Hypd.
      Hypd’s trademarks and trade dresses may not be used in connection with any
      product or service that is not Hypd’s, in any manner that is likely to
      cause confusion among users, or in any manner that disparages or
      discredits Hypd. All other trademarks not owned by Hypd that appear on
      this site are the property of their respective owners. Material on the App
      is solely for Your personal, non-commercial use. You must not copy,
      reproduce, republish, upload, post, transmit or distribute such material
      in any way, including by email or other electronic means and whether
      directly or indirectly and You must not assist any other person to do so.
      Without the prior written consent of the owner, modification of the
      materials, use of the materials on any other website or networked computer
      environment or use of the materials for any purpose other than personal,
      non-commercial use is a violation of the copyrights, trademarks and other
      proprietary rights, is strictly prohibited. Any use for which You receive
      any remuneration, whether in money or otherwise, is a commercial use for
      the purposes of this clause. Trademark complaint Hypd respects the
      intellectual property of others. In case you feel that your trademark has
      been infringed, you can write to Hypd at care@hypd.in Delivery Hypd will
      make a maximum of three attempts to deliver a FULL SIZED product ordered
      by you and a maximum of two attempts to deliver a SAMPLE ordered. In case
      the Buyer is not reachable or does not accept delivery of the Product or
      the Sample in these attempts, Hypd reserves the right to cancel the
      order(s) at its discretion. An estimated delivery time is displayed on the
      order summary page. On placing your order, you will receive an email
      containing a summary of the order and also the estimated delivery time to
      your location. Sometimes, delivery may take longer due to: bad weather,
      flight delays, political disruptions, or other unforeseen circumstances.
      In such cases, we will proactively reach out to you. Please check your
      emails and SMS regularly for such updates. Also, we will not be able to
      compensate for any mental agony caused due to delay in delivery. The Buyer
      can cancel the order at any moment of time even if the delivery time
      exceeds the expected delivery time. If it is a prepaid order, the Buyer
      will be refunded back the relevant transaction price in the account as
      soon as the order is successfully cancelled. The Buyer agrees that the
      title to a Product or Sample is transferred to the Buyer at the time of
      placing the order and dispatch confirmation thereof irrespective of
      shipping of the Product or Sample and cash on delivery, which are to be
      done in due course being separate chargeable facilities” Governing Law
      These Terms shall be governed by and constructed in accordance with the
      laws of India. Any disputes arising in relation hereto shall be subject to
      the exclusive jurisdiction of the courts at [New Delhi]. Interpretation of
      Number and Genders and Capitalised Words The Terms herein shall apply
      equally to both the singular and plural form of the terms defined.
      Whenever the context may require, any pronoun shall include the
      corresponding masculine and feminine. The words “include”, “includes” and
      “including” shall be deemed to be followed by the phrase “without
      limitation”. Unless the context otherwise requires, the terms “herein”,
      “hereof”, “hereto”, “hereunder” and words of similar import refer to the
      Terms as a whole. The capitalised words used anywhere in these Terms shall
      have the meaning as is readily inferable from the context or as they are
      commonly used and understood in their normal commercial sense. Headings
      The headings and subheadings herein are included for convenience and
      identification only and are not intended to describe, interpret, define or
      limit the scope, extent or intent of the Terms or the right to use the App
      by you contained herein or any other section or pages of the App or any
      Linked Sites in any manner whatsoever. Severability If any provision of
      the Terms is determined to be invalid or unenforceable in whole or in
      part, such invalidity or unenforceability shall attach only to such
      provision or part of such provision and the remaining part of such
      provision and all other provisions of these Terms shall continue to be in
      full force and effect. Report Abuse As per these Terms, users are solely
      responsible for every material or content uploaded on to the App. Hypd
      does not review the contents in any way before they appear through the
      App. Hypd does not verify, endorse or otherwise vouch for the contents of
      any user or any content generally posted or uploaded on to the App. Users
      can be held legally liable for their contents and may be held legally
      accountable if their contents or material include, for example, defamatory
      comments or material protected by copyright, trademark, etc. If you come
      across any abuse or violation of these Terms, please report to Hypd.
      Unauthorised Charges on your card If you see charges on your credit/debit
      card for purchases made through the App, but you never created an account
      or signed up, please check with your family members or business colleagues
      authorised to make purchases on your behalf, to confirm that they haven't
      placed the order. If you are still unable to recognise2 the charge, please
      report the unauthorised purchase to Hypd within [•] days of the
      transaction to enable Hypd to begin an investigation. Prohibited Uses You
      agree not to use the App in any way that is unlawful, illegal or
      unauthorised; is defamatory of any other person; is obscene or offensive;
      promotes discrimination based on race, sex, religion, nationality,
      disability, sexual orientation or age; infringes any copyright, database
      right or trade mark of any other person; is likely to harass, upset,
      embarrass, alarm or annoy any other person; is likely to disrupt our
      service in any way; or advocates, promotes or assists any unlawful act
      such as (by way of example only) copyright infringement or computer
      misuse. Mispricing Despite our best efforts, a small number of Products in
      our catalogue are mispriced. However, we verify prices as part of our
      shipping procedures. If a Product’s correct price is lower than our stated
      price, we charge the lower amount and send you the Product along with a
      refund of the excess amount as per these Terms. If a Product's correct
      price is higher than our stated price, we will cancel your order and
      notify you of that cancellation. POLICIES PROFANITY POLICY Hypd prohibits
      the use of language that is obscene, racist, hateful or otherwise
      disparaging in nature in any manner whatsoever. • This policy is
      applicable text within listings, on Seller pages and all other areas of
      the site that another User may view. If the profane words are part of a
      title for the item being sold, we allow Sellers to 'blur' out the bulk of
      the offending word with asterisks. • If a feedback comment, or any
      communication made between Users through the App; or email communication
      between Users in relation to transactions conducted on the App contain
      profane language, please submit a request for action/removal. •
      Disciplinary action may result in either an indefinite suspension of a
      User's account, a temporary suspension, or a formal warning. • Hypd will
      consider the circumstances of an alleged policy violation and the User's
      trading records before taking action. • Violations of this policy may
      result in a range of actions, including, limits placed on account
      privileges, loss of special status and account suspension. DISPUTE
      RESOLUTION POLICY Overview Generally, transactions are conducted smoothly
      on the App. However there may be some cases where both the Buyers and
      Sellers may face issues. At Hypd, we have a Dispute Resolution process in
      order to resolve disputes between Buyers and Sellers. What is a 'dispute'?
      A 'Dispute' can be defined as a disagreement between a Buyer and a Seller
      in connection with a transaction on the App. How does a 'dispute' occur in
      the Marketplace? Disputes are filed as a result of a disagreement between
      the Buyer and the Seller. Disputes arise out of an issue that is raised by
      either party not being completely satisfied with the resolution of their
      complaint/issue. It is important that before a Buyer/Seller raises a
      dispute, they should attempt to resolve the issue mutually. Please note
      that whenever a Buyer raises a dispute, the Seller's payment for that
      order is put on hold immediately until the issue is resolved. How is a
      'dispute' created? Whenever there is a disagreement, the Buyer can write
      to [•], while the Seller can write to [•], in order to raise a dispute.
      Disputes can be raised at any particular stage of the transaction. What
      are the various types of 'disputes'? Following are the indicative examples
      of potential disputes: Wrong item received Seller
      description/specification is wrong Damaged item Part/Accessory missing In
      case the Seller rejects the return request of the Buyer, and Buyer raises
      a dispute, then Hypd will try to mediate and resolve the dispute between
      both the parties. If the dispute is resolved in favour of the Buyer, a
      refund is provided once the product is returned to the Seller. If the
      dispute is settled in favour of the Seller, Buyer is not entitled to any
      refund. Disclaimer It is the User’s responsibility to log-in earlier if
      they want to avail better Products or Samples or styles because placement
      of orders is “first come, first served”. The merchandise is not restocked
      once sold out. No information regarding the presence of any Product or
      Sample in our stock will be guaranteed and we will alert you only when an
      item is sold out. We, as an intermediary digital marketplace, shall be
      under no liability whatsoever in respect of any loss or damage arising
      directly or indirectly out of the decline of authorisation for any
      transaction, or on account of the cardholder having exceeded the preset
      limit mutually agreed by us with our acquiring bank from time to time.
    </p>
  </div>
</template>

<script setup>
definePageMeta({
  name: "TermsAndConditions",
  layout: "public",
});

useSeoMeta({
  title: "Terms & Conditions | HYPD | #getHYPD",
  ogTitle: "Terms & Conditions | HYPD | #getHYPD",
  twitterTitle: "Terms & Conditions | HYPD | #getHYPD",
})
</script>

<style scoped>
div.page-wrapper {
  padding: 16px 32px;
  max-width: 1180px;
  margin: 0 auto;
  box-sizing: border-box;
}

h1.page-title {
  font-family: Urbanist-Bold;
  font-size: 36px;
  text-align: center;
}

p.page-content {
  text-align: justify;
  font-family: Urbanist-Medium;
}
</style>